import { describe, it, expect } from 'vitest'
import { classifyEntry, isSystemMessage } from '../../src/core/classifier.js'
import type { RawJsonlEntry } from '../../src/core/types.js'

describe('Edge cases: isMeta flag', () => {
  it('treats isMeta=true user messages as system role', () => {
    const entry: RawJsonlEntry = {
      type: 'user',
      uuid: 'meta-001',
      parentUuid: null,
      isSidechain: false,
      isMeta: true,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:00.000Z',
      message: {
        role: 'user',
        content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
      },
    }
    expect(isSystemMessage(entry)).toBe(true)
    const msgs = classifyEntry(entry, 1)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.role).toBe('system')
    expect(msgs[0]!.isMeta).toBe(true)
  })
})

describe('Edge cases: string content in user messages', () => {
  it('classifies command messages with string content', () => {
    const entry: RawJsonlEntry = {
      type: 'user',
      uuid: 'cmd-001',
      parentUuid: 'prev-uuid',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:00.000Z',
      message: {
        role: 'user',
        content: '<command-message>init</command-message>\n<command-name>/init</command-name>',
      },
    }
    const msgs = classifyEntry(entry, 5)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.role).toBe('system')
    expect(msgs[0]!.isMeta).toBe(true)
    expect(msgs[0]!.type).toBe('text')
  })

  it('preserves plan content field on plan mode user messages', () => {
    const entry: RawJsonlEntry = {
      type: 'user',
      uuid: 'plan-001',
      parentUuid: null,
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:00.000Z',
      planContent: '# Plan: Build feature X\n## Steps\n1. Do A\n2. Do B',
      message: {
        role: 'user',
        content: [{ type: 'text', text: 'Implement the following plan:\n\n# Plan: Build feature X' }],
      },
    }
    const msgs = classifyEntry(entry, 1)
    // It's a system message because it starts with "Implement the following plan:"
    expect(msgs[0]!.role).toBe('system')
    expect(msgs[0]!.planContent).toBe('# Plan: Build feature X\n## Steps\n1. Do A\n2. Do B')
  })
})

describe('Edge cases: compact_boundary system messages', () => {
  it('classifies compact_boundary as compact type', () => {
    const entry: RawJsonlEntry = {
      type: 'system',
      subtype: 'compact_boundary',
      uuid: 'compact-001',
      parentUuid: null,
      logicalParentUuid: 'prev-msg-001',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:05:00.000Z',
      content: 'Conversation compacted',
      isMeta: false,
      level: 'info',
      compactMetadata: {
        trigger: 'auto',
        preTokens: 171602,
      },
    }
    const msgs = classifyEntry(entry, 20)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.type).toBe('compact')
    expect(msgs[0]!.systemSubtype).toBe('compact_boundary')
    expect(msgs[0]!.text).toBe('Conversation compacted')
    expect(msgs[0]!.compactTrigger).toBe('auto')
    expect(msgs[0]!.compactPreTokens).toBe(171602)
    // Should use logicalParentUuid when parentUuid is null
    expect(msgs[0]!.parentUuid).toBe('prev-msg-001')
  })

  it('classifies microcompact_boundary with token savings', () => {
    const entry: RawJsonlEntry = {
      type: 'system',
      subtype: 'microcompact_boundary',
      uuid: 'micro-001',
      parentUuid: 'some-parent',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:03:00.000Z',
      content: 'Context microcompacted',
      isMeta: false,
      microcompactMetadata: {
        trigger: 'auto',
        preTokens: 61975,
        tokensSaved: 23783,
        compactedToolIds: ['Bash-abc', 'Read-def'],
        clearedAttachmentUUIDs: [],
      },
    }
    const msgs = classifyEntry(entry, 15)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.type).toBe('compact')
    expect(msgs[0]!.systemSubtype).toBe('microcompact_boundary')
    expect(msgs[0]!.compactTokensSaved).toBe(23783)
    expect(msgs[0]!.compactPreTokens).toBe(61975)
  })
})

describe('Edge cases: stop_hook_summary', () => {
  it('classifies stop_hook_summary with hook count', () => {
    const entry: RawJsonlEntry = {
      type: 'system',
      subtype: 'stop_hook_summary',
      uuid: 'hook-sum-001',
      parentUuid: 'msg-001',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T11:00:00.000Z',
      hookCount: 3,
      hookInfos: [
        { command: 'node check-console.js' },
        { command: 'python stop.py' },
      ],
      hookErrors: [],
      preventedContinuation: false,
      stopReason: '',
      hasOutput: true,
      level: 'suggestion',
    }
    const msgs = classifyEntry(entry, 50)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.type).toBe('system')
    expect(msgs[0]!.systemSubtype).toBe('stop_hook_summary')
    expect(msgs[0]!.hookCount).toBe(3)
    expect(msgs[0]!.preventedContinuation).toBe(false)
  })
})

describe('Edge cases: progress subtypes', () => {
  it('classifies hook_progress with event details', () => {
    const entry: RawJsonlEntry = {
      type: 'progress',
      uuid: 'hook-prog-001',
      parentUuid: 'user-001',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:01.000Z',
      data: {
        type: 'hook_progress',
        hookEvent: 'SessionStart',
        hookName: 'SessionStart:clear',
        command: 'node "${CLAUDE_PLUGIN_ROOT}/scripts/hooks/session-start.js"',
      },
      toolUseID: 'tool-hook-001',
    }
    const msgs = classifyEntry(entry, 2)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.type).toBe('progress')
    expect(msgs[0]!.progressType).toBe('hook_progress')
    expect(msgs[0]!.hookEvent).toBe('SessionStart')
    expect(msgs[0]!.hookName).toBe('SessionStart:clear')
  })

  it('classifies agent_progress with agentId and prompt', () => {
    const entry: RawJsonlEntry = {
      type: 'progress',
      uuid: 'agent-prog-001',
      parentUuid: 'tool-use-001',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:01:00.000Z',
      data: {
        type: 'agent_progress',
        agentId: 'ae7dadd',
        prompt: 'Research the topic and return findings',
        message: { type: 'user', message: { role: 'user', content: [] } },
      },
      toolUseID: 'toolu-agent-001',
    }
    const msgs = classifyEntry(entry, 8)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.type).toBe('progress')
    expect(msgs[0]!.progressType).toBe('agent_progress')
    expect(msgs[0]!.agentId).toBe('ae7dadd')
    expect(msgs[0]!.agentPrompt).toBe('Research the topic and return findings')
  })

  it('classifies waiting_for_task progress', () => {
    const entry: RawJsonlEntry = {
      type: 'progress',
      uuid: 'wait-001',
      parentUuid: null,
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:30.000Z',
      data: {
        type: 'waiting_for_task',
        taskDescription: 'Check Rust compilation',
        taskType: 'local_bash',
      },
    }
    const msgs = classifyEntry(entry, 6)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.progressType).toBe('waiting_for_task')
  })
})

describe('Edge cases: session continuation', () => {
  it('classifies session continuation notice as system role', () => {
    const entry: RawJsonlEntry = {
      type: 'user',
      uuid: 'cont-001',
      parentUuid: null,
      isSidechain: false,
      sessionId: 'sess-new-001',
      timestamp: '2025-01-01T10:00:00.000Z',
      message: {
        role: 'user',
        content: [{
          type: 'text',
          text: 'This session is being continued from a previous conversation. Previous context: ...',
        }],
      },
    }
    const msgs = classifyEntry(entry, 1)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.role).toBe('system')
  })
})

describe('Edge cases: ide_selection injection', () => {
  it('classifies IDE selection context as system role', () => {
    const entry: RawJsonlEntry = {
      type: 'user',
      uuid: 'ide-001',
      parentUuid: 'prev-001',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:00.000Z',
      message: {
        role: 'user',
        content: [{ type: 'text', text: '<ide_selection>Selected text content</ide_selection>' }],
      },
    }
    const msgs = classifyEntry(entry, 10)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.role).toBe('system')
    expect(msgs[0]!.isMeta).toBe(true)
  })
})

describe('Edge cases: api_error system message', () => {
  it('extracts error text from api_error system message', () => {
    const entry: RawJsonlEntry = {
      type: 'system',
      subtype: 'api_error',
      uuid: 'err-001',
      parentUuid: 'msg-001',
      isSidechain: false,
      sessionId: 'sess-001',
      timestamp: '2025-01-01T10:00:00.000Z',
      content: 'Error 529: Overloaded',
      isMeta: false,
      level: 'error',
    }
    const msgs = classifyEntry(entry, 30)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]!.type).toBe('system')
    expect(msgs[0]!.systemSubtype).toBe('api_error')
    expect(msgs[0]!.text).toBe('Error 529: Overloaded')
  })
})
